/*------------------------------------------------------------------
//The design file is generated by gen_top.py
//The design file including:
//--./test/test_temp.v;
//--./test/test_temp_1.v;
-------------------------------------------------------------------*/

module top (
	input		clk,	//to: ['test_temp']; 
	input		rst_n,	//to: ['test_temp', 'test_temp_1']; 
	input	[31:0] 	data_in,	//to: ['test_temp', 'test_temp_1']; 
	output		done,	//from: ['test_temp', 'test_temp_1']; 
	output	[31:0] 	data_out 	//from: ['test_temp_1']; 
);


//instance module of test_temp
test_temp u_test_temp (
	.clk	(clk),	 //input 
	.rst_n	(rst_n),	 //input 
	.data_in	(data_in),	 //input [31:0] 
	.done	(done)	// output 
);

//instance module of test_temp_1
test_temp_1 u_test_temp_1 (
	.rst_n	(rst_n),	 //input 
	.data_in	(data_in),	 //input [31:0] 
	.data_out	(data_out),	 //output [31:0] 
	.done	(done)	// output 
);

endmodule
