${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_params.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_bcm_params.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_derived_params.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_clk_mux_4x1.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_clk_mux_2x1.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_clk_and.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_clk_or.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_ahb2apb.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_regb.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_dma.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_cdet.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_2clk_fifoctl.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_biu.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_b2c.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_c2b.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_2clk_dssram.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_autostop.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_rxfifowr.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_txfiford.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_crc7.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_crc16.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_c2b2clk.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_intrcntl.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_clkcntl.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_clkmux_interleave.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_bcm21.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_bcm41.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_bcm05.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_bcm07.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_bcm57.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_bcm66.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_datastrobe.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_muxdemux.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_cmdpath.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_datatx.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_datarx.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_datapath.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_ciu.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_dmac_if.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_dmac_csr.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_dmac_cntrl.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_ahb_ahm.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc_dmac_ahb.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc.v
${SOC_WS}/design/mmc_ss/rtl/mmc/ud_mmc-undef.v

-f ${SOC_WS}/design/mem/vlogfile.f
